/**
 * Registry of playable MUGEN characters. Each entry points at a folder served
 * from the @3xl/assets package (manifest.json + frame PNGs) under `/assets/`.
 *
 * GENERATED by @3xl/mugen's import-mugen.js from the character definitions in
 * @3xl/data's public/characters/*.json — run `pnpm import:mugen` to add
 * characters rather than editing this file by hand.
 */
import type { CharacterOption } from './index';

export const registry: CharacterOption[] = [
	{ id: 'brook', label: 'Brook', basePath: '/assets/brook/frames' },
	{ id: 'chopper', label: 'Chopper', basePath: '/assets/chopper/frames' },
	{ id: 'ccellv1100', label: 'Complete Cell', basePath: '/assets/ccellv1100/frames' },
	{ id: 'franky', label: 'Franky', basePath: '/assets/franky/frames' },
	{ id: 'jaken', label: 'Jaken', basePath: '/assets/jaken/frames' },
	{ id: 'kagome', label: 'Kagome', basePath: '/assets/kagome/frames' },
	{ id: 'kagura', label: 'Kagura RP', basePath: '/assets/kagura/frames' },
	{ id: 'kikyo', label: 'Kikyo', basePath: '/assets/kikyo/frames' },
	{ id: 'koga', label: 'Koga', basePath: '/assets/koga/frames' },
	{ id: 'luffy', label: 'Monkey D. Luffy', basePath: '/assets/luffy/frames' },
	{ id: 'nami', label: 'Nami', basePath: '/assets/nami/frames' },
	{ id: 'crappy-naraku', label: 'Naraku', basePath: '/assets/crappy-naraku/frames' },
	{ id: 'piccolo1v1100', label: 'Piccolo sb1', basePath: '/assets/piccolo1v1100/frames' },
	{ id: 'ranmahb', label: 'Ranma Saotome', basePath: '/assets/ranmahb/frames' },
	{ id: 'zoro', label: 'Roronoa Zoro', basePath: '/assets/zoro/frames' },
	{ id: 'sailormarsk110809', label: 'Sailor Mars K', basePath: '/assets/sailormarsk110809/frames' },
	{
		id: 'sailormercury-a-hsm',
		label: 'Sailor Mercury A',
		basePath: '/assets/sailormercury-a-hsm/frames'
	},
	{ id: 'moon', label: 'Sailor Moon', basePath: '/assets/moon/frames' },
	{ id: 'sango', label: 'Sango', basePath: '/assets/sango/frames' },
	{ id: 'sanji', label: 'Sanji', basePath: '/assets/sanji/frames' },
	{ id: 'sb1gokuanotherlive', label: 'SonGoku-Snk/SF', basePath: '/assets/sb1gokuanotherlive/frames' },
	{ id: 'trunkssb1v1100', label: 'Trunks sb1', basePath: '/assets/trunkssb1v1100/frames' },
	{ id: 'usopp', label: 'Usopp', basePath: '/assets/usopp/frames' },
	{ id: 'vegetassj1v1100', label: 'Vegeta SSJ1', basePath: '/assets/vegetassj1v1100/frames' }
];
