/**
 * Registry of playable MUGEN characters. Each entry points at a folder served
 * from the @3xl/assets package (manifest.json + frame PNGs) under `/assets/`.
 *
 * GENERATED by @3xl/mugen's import-mugen.js from the character definitions in
 * @3xl/data's public/characters/<id>/definition.json — run `pnpm import:mugen` to add
 * characters rather than editing this file by hand.
 */
import type { CharacterOption } from './index';

export const registry: CharacterOption[] = [
	{ id: 'g6-androide-18', label: 'Android 18', basePath: '/assets/g6-androide-18/frames' },
	{ id: 'beauty', label: 'Beauty', basePath: '/assets/beauty/frames' },
	{ id: 'captain-battleship', label: 'Captain Battleship', basePath: '/assets/captain-battleship/frames' },
	{ id: 'chopper', label: 'Chopper', basePath: '/assets/chopper/frames' },
	{ id: 'denbo', label: 'Denbo', basePath: '/assets/denbo/frames' },
	{ id: 'dengaku-man', label: 'Dengaku Man', basePath: '/assets/dengaku-man/frames' },
	{ id: 'fatbuu', label: 'Fat Buu', basePath: '/assets/fatbuu/frames' },
	{ id: 'frieza', label: 'Frieza', basePath: '/assets/frieza/frames' },
	{ id: 'gokufz', label: 'Goku', basePath: '/assets/gokufz/frames' },
	{ id: 'gotenks', label: 'Gotenks', basePath: '/assets/gotenks/frames' },
	{ id: 'hair-hunter', label: 'Hair Hunt Troop', basePath: '/assets/hair-hunter/frames' },
	{ id: 'halekulani', label: 'Halekulani', basePath: '/assets/halekulani/frames' },
	{ id: 'hatenko', label: 'Hatenko', basePath: '/assets/hatenko/frames' },
	{ id: 'inuyasha', label: 'Inuyasha', basePath: '/assets/inuyasha/frames' },
	{ id: 'jelly-jiggler', label: 'Jelly', basePath: '/assets/jelly-jiggler/frames' },
	{ id: 'kagome', label: 'Kagome', basePath: '/assets/kagome/frames' },
	{ id: 'kagura', label: 'Kagura RP', basePath: '/assets/kagura/frames' },
	{ id: 'kikyo', label: 'Kikyo', basePath: '/assets/kikyo/frames' },
	{ id: 'koga', label: 'Koga', basePath: '/assets/koga/frames' },
	{ id: 'krillin', label: 'Krillin', basePath: '/assets/krillin/frames' },
	{ id: 'miroku', label: 'Miroku', basePath: '/assets/miroku/frames' },
	{ id: 'luffy', label: 'Monkey D. Luffy', basePath: '/assets/luffy/frames' },
	{ id: 'nami', label: 'Nami', basePath: '/assets/nami/frames' },
	{ id: 'eb-perfectcell-kofm', label: 'Perfect Cell', basePath: '/assets/eb-perfectcell-kofm/frames' },
	{ id: 'piccolo', label: 'Piccolo', basePath: '/assets/piccolo/frames' },
	{ id: 'zoro', label: 'Roronoa Zoro', basePath: '/assets/zoro/frames' },
	{ id: 'sango', label: 'Sango', basePath: '/assets/sango/frames' },
	{ id: 'sanji', label: 'Sanji', basePath: '/assets/sanji/frames' },
	{ id: 'service-man', label: 'Service Man', basePath: '/assets/service-man/frames' },
	{ id: 'seshomaru', label: 'Sesshomaru', basePath: '/assets/seshomaru/frames' },
	{ id: 'softon', label: 'Softon', basePath: '/assets/softon/frames' },
	{ id: 'supervegeta', label: 'Super Vegeta', basePath: '/assets/supervegeta/frames' },
	{ id: 'torpedo-girl', label: 'Torpedo Girl', basePath: '/assets/torpedo-girl/frames' },
	{ id: 'eb-trunks', label: 'Trunks SSJ', basePath: '/assets/eb-trunks/frames' },
	{ id: 'youkai-inuyasha', label: 'Youkai Inuyasha', basePath: '/assets/youkai-inuyasha/frames' }
];
