<script lang="ts">
	import classNames from 'classnames';
	import { browser } from '$app/environment';
	import MugenFrameSheet from '$components/core/MugenFrameSheet.svelte';
	import CharacterGridCard from '$components/core/CharacterGridCard.svelte';
	import CharacterDefinitionEditor from '$components/core/CharacterDefinitionEditor.svelte';
	import CharacterStatsEditor from '$components/core/CharacterStatsEditor.svelte';
	import MugenImportedMoves from '$components/core/MugenImportedMoves.svelte';
	import { characters, defaultCharacterId } from '@3xl/data';
	import type { CharacterOption } from '@3xl/data';
	import type { CharacterDefinition } from '$types/character-definition.type';
	import type { MugenImportedMoveset } from '$types/mugen-move.type';

	// The character read/write API is served by @3xl/backend (default :2002).
	// Static assets (/data, manifests) stay same-origin, served by this app's vite.
	const API_BASE = import.meta.env.VITE_API_BASE ?? 'http://localhost:2002';

	let selectedId = defaultCharacterId;
	let activeTab: 'definition' | 'stats' | 'frames' | 'imported' = 'definition';

	$: selected = characters.find((character) => character.id === selectedId) ?? characters[0];

	// Definition + editor state for the selected character. All loading happens in
	// the browser only — the write API lives behind `vite dev` and must not be hit
	// during static prerender.
	let definition: CharacterDefinition | null = null;
	let availableAnimations: string[] = [];
	let moveset: MugenImportedMoveset | null = null;
	let loadError = '';
	let saving = false;
	let saveError = '';

	async function load(character: CharacterOption) {
		definition = null;
		availableAnimations = [];
		moveset = null;
		loadError = '';
		saveError = '';
		try {
			const [defRes, manifestRes, movesRes] = await Promise.all([
				fetch(`${API_BASE}/api/characters/${character.id}`),
				fetch(`${character.basePath}/manifest.json`),
				// Generated by scripts/import-mugen.js; absent until a re-import.
				fetch(`/data/characters/${character.id}/mugen-moves.json`)
			]);
			if (!defRes.ok) throw new Error(`Failed to load definition (${defRes.status})`);
			definition = (await defRes.json()) as CharacterDefinition;
			if (manifestRes.ok) {
				const manifest = await manifestRes.json();
				availableAnimations = Object.keys(manifest.animations ?? {});
			}
			if (movesRes.ok) {
				moveset = (await movesRes.json()) as MugenImportedMoveset;
			}
		} catch (error) {
			loadError = error instanceof Error ? error.message : String(error);
		}
	}

	// Re-load whenever the selected character changes (browser only).
	$: if (browser) load(selected);

	async function handleSave(event: CustomEvent<CharacterDefinition>) {
		saving = true;
		saveError = '';
		try {
			const res = await fetch(`${API_BASE}/api/characters/${event.detail.id}`, {
				method: 'POST',
				headers: { 'content-type': 'application/json' },
				body: JSON.stringify(event.detail)
			});
			if (!res.ok) {
				const body = await res.json().catch(() => ({ message: res.statusText }));
				throw new Error(body.message ?? 'Save failed');
			}
			definition = (await res.json()) as CharacterDefinition;
		} catch (error) {
			saveError = error instanceof Error ? error.message : String(error);
		} finally {
			saving = false;
		}
	}
</script>

<div class="min-h-screen bg-base-200 p-6 md:p-10">
	<div class="mx-auto flex max-w-6xl flex-col gap-6">
		<header class="flex flex-col gap-2">
			<div class="flex items-center gap-3">
				<h1 class="text-3xl font-bold">Character frames</h1>
				<span class="badge badge-neutral">{characters.length} characters</span>
			</div>
			<p class="text-sm opacity-70">
				Every animation each character defines, looping live on a PixiJS canvas with its static
				frames laid out beside it.
			</p>
			<a class="link link-primary text-sm" href="/">← Back to stage</a>
		</header>

		<div
			class="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5"
		>
			{#each characters as character (character.id)}
				<CharacterGridCard
					{character}
					selected={character.id === selectedId}
					on:select={(event) => (selectedId = event.detail.id)}
				/>
			{/each}
		</div>

		<div role="tablist" class="tabs tabs-boxed w-fit">
			<button
				role="tab"
				class={classNames('tab', { 'tab-active': activeTab === 'definition' })}
				on:click={() => (activeTab = 'definition')}
			>
				Definition
			</button>
			<button
				role="tab"
				class={classNames('tab', { 'tab-active': activeTab === 'stats' })}
				on:click={() => (activeTab = 'stats')}
			>
				Stats
			</button>
			<button
				role="tab"
				class={classNames('tab', { 'tab-active': activeTab === 'frames' })}
				on:click={() => (activeTab = 'frames')}
			>
				Frames
			</button>
			<button
				role="tab"
				class={classNames('tab', { 'tab-active': activeTab === 'imported' })}
				on:click={() => (activeTab = 'imported')}
			>
				Imported
			</button>
		</div>

		<section class={classNames('card bg-base-100 shadow-xl', { hidden: activeTab !== 'definition' })}>
			<div class="card-body gap-4">
				<div class="flex items-center gap-3">
					<h2 class="card-title">{selected.label} — definition</h2>
					<span class="badge badge-ghost font-mono text-xs">/characters/{selected.id}.json</span>
				</div>
				<p class="text-sm opacity-70">
					Bind this character's movement animations and combat moves to raw MUGEN animations, then
					save straight into the git tree.
				</p>

				{#if loadError}
					<div class="alert alert-error">
						<span>{loadError}</span>
					</div>
				{:else if definition}
					{#key definition.id}
						<CharacterDefinitionEditor
							{definition}
							basePath={selected.basePath}
							{availableAnimations}
							{saving}
							errorMessage={saveError}
							on:save={handleSave}
						/>
					{/key}
				{:else}
					<div class="flex items-center gap-2 opacity-70">
						<span class="loading loading-spinner loading-sm"></span>
						<span>Loading definition…</span>
					</div>
				{/if}
			</div>
		</section>

		<section class={classNames('card bg-base-100 shadow-xl', { hidden: activeTab !== 'stats' })}>
			<div class="card-body gap-4">
				<div class="flex items-center gap-3">
					<h2 class="card-title">{selected.label} — stats</h2>
					<span class="badge badge-ghost font-mono text-xs">/characters/{selected.id}.json</span>
				</div>
				<p class="text-sm opacity-70">
					Tune this character's core gameplay stats and save straight into the git tree.
				</p>

				{#if loadError}
					<div class="alert alert-error">
						<span>{loadError}</span>
					</div>
				{:else if definition}
					{#key definition.id}
						<CharacterStatsEditor
							{definition}
							{saving}
							errorMessage={saveError}
							on:save={handleSave}
						/>
					{/key}
				{:else}
					<div class="flex items-center gap-2 opacity-70">
						<span class="loading loading-spinner loading-sm"></span>
						<span>Loading definition…</span>
					</div>
				{/if}
			</div>
		</section>

		{#if activeTab === 'frames'}
			<section class="card bg-base-100 shadow-xl">
				<div class="card-body gap-4">
					<div class="flex items-center gap-3">
						<h2 class="card-title">{selected.label} — frames</h2>
						<span class="badge badge-ghost font-mono text-xs">{selected.basePath}</span>
					</div>
					<!-- Remount on character change so Pixi tears down and reloads cleanly. -->
					{#key selected.id}
						<MugenFrameSheet basePath={selected.basePath} />
					{/key}
				</div>
			</section>
		{/if}

		{#if activeTab === 'imported'}
			<section class="card bg-base-100 shadow-xl">
				<div class="card-body gap-4">
					<div class="flex items-center gap-3">
						<h2 class="card-title">{selected.label} — imported moves</h2>
						<span class="badge badge-ghost font-mono text-xs">/data/characters/{selected.id}/mugen-moves.json</span>
					</div>
					<p class="text-sm opacity-70">
						The raw MUGEN moveset extracted at import time from the character's .cmd and state
						files — every command-triggered state with its input, damage and animation. Read-only.
					</p>

					{#if loadError}
						<div class="alert alert-error">
							<span>{loadError}</span>
						</div>
					{:else if moveset}
						{#key selected.id}
							<MugenImportedMoves {moveset} basePath={selected.basePath} />
						{/key}
					{:else}
						<div class="alert alert-info">
							<span>
								No imported move data for this character — re-run
								<code class="font-mono">pnpm import:mugen {selected.id}</code> to extract it.
							</span>
						</div>
					{/if}
				</div>
			</section>
		{/if}
	</div>
</div>
