import { writable } from 'svelte/store';
import type { CharacterOption } from '@3xl/data';
import type { CharacterDefinition } from '$types/character-definition.type';
import type { MugenImportedMoveset } from '$types/mugen-move.type';

/**
 * Everything the four per-character detail views read: the character's editable
 * definition, the animation names its decoded manifest offers, and the raw
 * moveset the MUGEN import extracted.
 *
 * One character's worth at a time — the detail routes show a single character —
 * so the state carries the `id` it belongs to and consumers can tell a loaded
 * character from the previous one still on screen.
 *
 * The definition read/write API is served by @3xl/backend (default :2002); the
 * manifest and moveset are static, served same-origin by this app's vite.
 */
export interface CharacterDetailState {
	/** Which character the rest of this state describes; empty before any load. */
	id: string;
	definition: CharacterDefinition | null;
	/** Animation keys from the character's decoded manifest, for the editor's pickers. */
	availableAnimations: string[];
	/** The raw imported moveset, or null when the character has none on disk. */
	moveset: MugenImportedMoveset | null;
	loadError: string;
	saving: boolean;
	saveError: string;
}

const API_BASE = import.meta.env.VITE_API_BASE ?? 'http://localhost:2002';

const empty: CharacterDetailState = {
	id: '',
	definition: null,
	availableAnimations: [],
	moveset: null,
	loadError: '',
	saving: false,
	saveError: ''
};

export const characterDetail = writable<CharacterDetailState>(empty);

/**
 * Load one character's definition, manifest animations and imported moveset.
 * Browser only — the write API lives behind `vite dev` and must never be hit
 * during a static prerender, so callers guard on `browser`.
 */
export async function loadCharacterDetail(character: CharacterOption): Promise<void> {
	characterDetail.set({ ...empty, id: character.id });
	try {
		const [defRes, manifestRes, movesRes] = await Promise.all([
			fetch(`${API_BASE}/api/characters/${character.id}`),
			fetch(`${character.basePath}/manifest.json`),
			// Generated by scripts/import-mugen.js; absent until a re-import.
			fetch(`/data/characters/${character.id}/mugen-moves.json`)
		]);
		if (!defRes.ok) throw new Error(`Failed to load definition (${defRes.status})`);
		const definition = (await defRes.json()) as CharacterDefinition;
		const availableAnimations = manifestRes.ok
			? Object.keys(((await manifestRes.json()) as { animations?: object }).animations ?? {})
			: [];
		const moveset = movesRes.ok ? ((await movesRes.json()) as MugenImportedMoveset) : null;
		characterDetail.update((state) =>
			// A slower load for a character that is no longer the one on screen is
			// dropped rather than shown against the newer one.
			state.id === character.id
				? { ...state, definition, availableAnimations, moveset }
				: state
		);
	} catch (error) {
		const loadError = error instanceof Error ? error.message : String(error);
		characterDetail.update((state) => (state.id === character.id ? { ...state, loadError } : state));
	}
}

/**
 * Remove one frame from one of the character's animations, straight out of the
 * decoded manifest in the git tree (frames are described there, not in the
 * definition — see the backend route). Returns whether the write landed, so a
 * caller can redraw only on success.
 *
 * Reported through the same `saving` / `saveError` fields a definition save uses:
 * from the author's side this is one more edit to the character on screen, and the
 * header spinner and error alert are already wired to them.
 */
export async function deleteCharacterFrame(
	id: string,
	animation: string,
	index: number
): Promise<boolean> {
	characterDetail.update((state) => ({ ...state, saving: true, saveError: '' }));
	try {
		const res = await fetch(
			`${API_BASE}/api/characters/${id}/frames/${encodeURIComponent(animation)}/${index}`,
			{ method: 'DELETE' }
		);
		if (!res.ok) {
			const body = (await res.json().catch(() => ({}))) as { message?: string };
			throw new Error(body.message ?? 'Delete failed');
		}
		characterDetail.update((state) => ({ ...state, saving: false }));
		return true;
	} catch (error) {
		const saveError = error instanceof Error ? error.message : String(error);
		characterDetail.update((state) => ({ ...state, saving: false, saveError }));
		return false;
	}
}

/**
 * Persist an edited definition straight into the git tree, and adopt what the
 * API echoes back as the new baseline.
 */
export async function saveCharacterDefinition(definition: CharacterDefinition): Promise<void> {
	characterDetail.update((state) => ({ ...state, saving: true, saveError: '' }));
	try {
		const res = await fetch(`${API_BASE}/api/characters/${definition.id}`, {
			method: 'POST',
			headers: { 'content-type': 'application/json' },
			body: JSON.stringify(definition)
		});
		if (!res.ok) {
			const body = (await res.json().catch(() => ({}))) as { message?: string };
			throw new Error(body.message ?? 'Save failed');
		}
		const saved = (await res.json()) as CharacterDefinition;
		characterDetail.update((state) =>
			state.id === saved.id ? { ...state, definition: saved, saving: false } : state
		);
	} catch (error) {
		const saveError = error instanceof Error ? error.message : String(error);
		characterDetail.update((state) => ({ ...state, saving: false, saveError }));
	}
}
