/**
 * Registry of playable MUGEN characters. Each entry points at a folder under
 * the static root produced by scripts/generate-sprites.js (manifest.json +
 * frame PNGs).
 *
 * This file is generated by scripts/import-mugen.js from the character
 * definitions in static/characters/*.json — run `pnpm import:mugen` to add
 * characters rather than editing it by hand.
 */
export interface CharacterOption {
	/** Stable id, matches the static/<id>/ folder name. */
	id: string;
	/** Human-readable name shown in the picker. */
	label: string;
	/** Folder (relative to the static root) with manifest.json + frames. */
	basePath: string;
}

export const characters: CharacterOption[] = [
	{ id: 'brook', label: 'Brook', basePath: '/brook/frames' },
	{ id: 'chopper', label: 'Chopper', basePath: '/chopper/frames' },
	{ id: 'ccellv1100', label: 'Complete Cell', basePath: '/ccellv1100/frames' },
	{ id: 'franky', label: 'Franky', basePath: '/franky/frames' },
	{ id: 'gokussj1v1100', label: 'Goku SSJ1', basePath: '/gokussj1v1100/frames' },
	{ id: 'hiei-g1-2018', label: 'Hiei_G1', basePath: '/hiei-g1-2018/frames' },
	{ id: 'jaken', label: 'Jaken', basePath: '/jaken/frames' },
	{ id: 'kagome', label: 'Kagome', basePath: '/kagome/frames' },
	{ id: 'kagura', label: 'Kagura RP', basePath: '/kagura/frames' },
	{ id: 'kgohanv1100', label: 'Kid Gohan SSJ1', basePath: '/kgohanv1100/frames' },
	{ id: 'kikyo', label: 'Kikyo', basePath: '/kikyo/frames' },
	{ id: 'koga', label: 'Koga', basePath: '/koga/frames' },
	{ id: 'kuramamega-g1', label: 'Kurama_G1', basePath: '/kuramamega-g1/frames' },
	{ id: 'kuwabara', label: 'Kuwabara Kazuma', basePath: '/kuwabara/frames' },
	{ id: 'kuwabara-vers-o-2018-2018', label: 'Kuwabara_G1', basePath: '/kuwabara-vers-o-2018-2018/frames' },
	{ id: 'mfriezav1100', label: 'Maximum Frieza', basePath: '/mfriezav1100/frames' },
	{ id: 'luffy', label: 'Monkey D. Luffy', basePath: '/luffy/frames' },
	{ id: 'moon-hsm', label: 'Moon', basePath: '/moon-hsm/frames' },
	{ id: 'nami', label: 'Nami', basePath: '/nami/frames' },
	{ id: 'crappy-naraku', label: 'Naraku', basePath: '/crappy-naraku/frames' },
	{ id: 'piccolo1v1100', label: 'Piccolo sb1', basePath: '/piccolo1v1100/frames' },
	{ id: 'ranma', label: 'Ranma', basePath: '/ranma/frames' },
	{ id: 'ranmachan', label: 'Ranma by Nyan Kiryu', basePath: '/ranmachan/frames' },
	{ id: 'ranmahb', label: 'Ranma Saotome', basePath: '/ranmahb/frames' },
	{ id: 'zoro', label: 'Roronoa Zoro', basePath: '/zoro/frames' },
	{ id: 'sailormarsk110809', label: 'Sailor Mars K', basePath: '/sailormarsk110809/frames' },
	{ id: 'sailormercury-a-hsm', label: 'Sailor Mercury A', basePath: '/sailormercury-a-hsm/frames' },
	{ id: 'moon', label: 'Sailor Moon', basePath: '/moon/frames' },
	{ id: 'sango', label: 'Sango', basePath: '/sango/frames' },
	{ id: 'sanji', label: 'Sanji', basePath: '/sanji/frames' },
	{ id: 'sb1gokuanotherlive', label: 'SonGoku-Snk/SF', basePath: '/sb1gokuanotherlive/frames' },
	{ id: 'trunkssb1v1100', label: 'Trunks sb1', basePath: '/trunkssb1v1100/frames' },
	{ id: 'usopp', label: 'Usopp', basePath: '/usopp/frames' },
	{ id: 'vegetassj1v1100', label: 'Vegeta SSJ1', basePath: '/vegetassj1v1100/frames' }
];

export const defaultCharacterId = characters[0].id;
